import React from 'react';
import s from './Block.styl';

class Block extends React.Component {
  render() {
    return (
      <div className={s.container}>
        <hr />
        <table>
          <tbody>
          <tr>
            <td>AF</td>
            <td>Afghanistan</td>
            <td>+93</td>
          </tr>
          <tr>
            <td>AL</td>
            <td>Albania</td>
            <td>+355</td>
          </tr>
          <tr>
            <td>DZ</td>
            <td>Algeria</td>
            <td>+213</td>
          </tr>
          <tr>
            <td>AS</td>
            <td>American Samoa</td>
            <td>+1</td>
          </tr>
          <tr>
            <td>AD</td>
            <td>Andorra</td>
            <td>+376</td>
          </tr>
          <tr>
            <td>AO</td>
            <td>Angola</td>
            <td>+244</td>
          </tr>
          <tr>
            <td>AG</td>
            <td>Antigua</td>
            <td>+1</td>
          </tr>
          <tr>
            <td>AR</td>
            <td>Argentina</td>
            <td>+54</td>
          </tr>
          <tr>
            <td>AM</td>
            <td>Armenia</td>
            <td>+374</td>
          </tr>
          <tr>
            <td>AW</td>
            <td>Aruba</td>
            <td>+297</td>
          </tr>
          <tr>
            <td>AU</td>
            <td>Australia</td>
            <td>+61</td>
          </tr>
          <tr>
            <td>AI</td>
            <td>Austria</td>
            <td>+43</td>
          </tr>
          <tr>
            <td>AZ</td>
            <td>Azerbaijan</td>
            <td>+994</td>
          </tr>
          <tr>
            <td>BH</td>
            <td>Bahrain</td>
            <td>+973</td>
          </tr>
          <tr>
            <td>BD</td>
            <td>Bangladesh</td>
            <td>+880</td>
          </tr>
          <tr>
            <td>BB</td>
            <td>Barbados</td>
            <td>+1</td>
          </tr>
          <tr>
            <td>BY</td>
            <td>Belarus</td>
            <td>+375</td>
          </tr>
          <tr>
            <td>BE</td>
            <td>Belgium</td>
            <td>+32</td>
          </tr>
          <tr>
            <td>BZ</td>
            <td>Belize</td>
            <td>+501</td>
          </tr>
          <tr>
            <td>BJ</td>
            <td>Benin</td>
            <td>+229</td>
          </tr>
          <tr>
            <td>BM</td>
            <td>Bermuda</td>
            <td>+1</td>
          </tr>
          <tr>
            <td>BT</td>
            <td>Bhutan</td>
            <td>+975</td>
          </tr>
          <tr>
            <td>BO</td>
            <td>Bolivia</td>
            <td>+591</td>
          </tr>
          <tr>
            <td>BA</td>
            <td>Bosnia and Herzegovina</td>
            <td>+387</td>
          </tr>
          <tr>
            <td>BW</td>
            <td>Botswana</td>
            <td>+267</td>
          </tr>
          <tr>
            <td>BR</td>
            <td>Brazil</td>
            <td>+55</td>
          </tr>
          <tr>
            <td>IO</td>
            <td>British Indian Ocean Territory</td>
            <td>+246</td>
          </tr>
          <tr>
            <td>VG</td>
            <td>British Virgin Islands</td>
            <td>+1</td>
          </tr>
          <tr>
            <td>BN</td>
            <td>Brunei</td>
            <td>+673</td>
          </tr>
          <tr>
            <td>BG</td>
            <td>Bulgaria</td>
            <td>+359</td>
          </tr>
          <tr>
            <td>BF</td>
            <td>Burkina Faso</td>
            <td>+226</td>
          </tr>
          <tr>
            <td>MM</td>
            <td>Burma Myanmar</td>
            <td>+95</td>
          </tr>
          <tr>
            <td>BI</td>
            <td>Burundi</td>
            <td>+257</td>
          </tr>
          <tr>
            <td>KH</td>
            <td>Cambodia</td>
            <td>+855</td>
          </tr>
          <tr>
            <td>CM</td>
            <td>Cameroon</td>
            <td>+237</td>
          </tr>
          <tr>
            <td>CA</td>
            <td>Canada</td>
            <td>+1</td>
          </tr>
          <tr>
            <td>CV</td>
            <td>Cape Verde</td>
            <td>+238</td>
          </tr>
          <tr>
            <td>KY</td>
            <td>Cayman Islands</td>
            <td>+1</td>
          </tr>
          <tr>
            <td>CF</td>
            <td>Central African Republic</td>
            <td>+236</td>
          </tr>
          <tr>
            <td>CL</td>
            <td>Chile</td>
            <td>+56</td>
          </tr>
          </tbody>
        </table>
      </div>
    );
  }
}

export default Block;
