import React from 'react';
import Page from '../../components/Page/Page';
import s from './Contacts.styl';

const Contacts = () => (
  <Page title="Contacts">
    <h1 className={s.title}>Contacts</h1>
    <p>This is the Contacts page</p>
    <table>
      <tbody>
      <tr>
        <td>AF</td>
        <td>Afghanistan</td>
        <td>+93</td>
      </tr>
      <tr>
        <td>AL</td>
        <td>Albania</td>
        <td>+355</td>
      </tr>
      <tr>
        <td>DZ</td>
        <td>Algeria</td>
        <td>+213</td>
      </tr>
      <tr>
        <td>AS</td>
        <td>American Samoa</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>AD</td>
        <td>Andorra</td>
        <td>+376</td>
      </tr>
      <tr>
        <td>AO</td>
        <td>Angola</td>
        <td>+244</td>
      </tr>
      <tr>
        <td>AG</td>
        <td>Antigua</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>AR</td>
        <td>Argentina</td>
        <td>+54</td>
      </tr>
      <tr>
        <td>AM</td>
        <td>Armenia</td>
        <td>+374</td>
      </tr>
      <tr>
        <td>AW</td>
        <td>Aruba</td>
        <td>+297</td>
      </tr>
      <tr>
        <td>AU</td>
        <td>Australia</td>
        <td>+61</td>
      </tr>
      <tr>
        <td>AI</td>
        <td>Austria</td>
        <td>+43</td>
      </tr>
      <tr>
        <td>AZ</td>
        <td>Azerbaijan</td>
        <td>+994</td>
      </tr>
      <tr>
        <td>BH</td>
        <td>Bahrain</td>
        <td>+973</td>
      </tr>
      <tr>
        <td>BD</td>
        <td>Bangladesh</td>
        <td>+880</td>
      </tr>
      <tr>
        <td>BB</td>
        <td>Barbados</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>BY</td>
        <td>Belarus</td>
        <td>+375</td>
      </tr>
      <tr>
        <td>BE</td>
        <td>Belgium</td>
        <td>+32</td>
      </tr>
      <tr>
        <td>BZ</td>
        <td>Belize</td>
        <td>+501</td>
      </tr>
      <tr>
        <td>BJ</td>
        <td>Benin</td>
        <td>+229</td>
      </tr>
      <tr>
        <td>BM</td>
        <td>Bermuda</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>BT</td>
        <td>Bhutan</td>
        <td>+975</td>
      </tr>
      <tr>
        <td>BO</td>
        <td>Bolivia</td>
        <td>+591</td>
      </tr>
      <tr>
        <td>BA</td>
        <td>Bosnia and Herzegovina</td>
        <td>+387</td>
      </tr>
      <tr>
        <td>BW</td>
        <td>Botswana</td>
        <td>+267</td>
      </tr>
      <tr>
        <td>BR</td>
        <td>Brazil</td>
        <td>+55</td>
      </tr>
      <tr>
        <td>IO</td>
        <td>British Indian Ocean Territory</td>
        <td>+246</td>
      </tr>
      <tr>
        <td>VG</td>
        <td>British Virgin Islands</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>BN</td>
        <td>Brunei</td>
        <td>+673</td>
      </tr>
      <tr>
        <td>BG</td>
        <td>Bulgaria</td>
        <td>+359</td>
      </tr>
      <tr>
        <td>BF</td>
        <td>Burkina Faso</td>
        <td>+226</td>
      </tr>
      <tr>
        <td>MM</td>
        <td>Burma Myanmar</td>
        <td>+95</td>
      </tr>
      <tr>
        <td>BI</td>
        <td>Burundi</td>
        <td>+257</td>
      </tr>
      <tr>
        <td>KH</td>
        <td>Cambodia</td>
        <td>+855</td>
      </tr>
      <tr>
        <td>CM</td>
        <td>Cameroon</td>
        <td>+237</td>
      </tr>
      <tr>
        <td>CA</td>
        <td>Canada</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>CV</td>
        <td>Cape Verde</td>
        <td>+238</td>
      </tr>
      <tr>
        <td>KY</td>
        <td>Cayman Islands</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>CF</td>
        <td>Central African Republic</td>
        <td>+236</td>
      </tr>
      <tr>
        <td>CL</td>
        <td>Chile</td>
        <td>+56</td>
      </tr>
      <tr>
        <td>CN</td>
        <td>China</td>
        <td>+86</td>
      </tr>
      <tr>
        <td>CO</td>
        <td>Colombia</td>
        <td>+57</td>
      </tr>
      <tr>
        <td>KM</td>
        <td>Comoros</td>
        <td>+269</td>
      </tr>
      <tr>
        <td>CK</td>
        <td>Cook Islands</td>
        <td>+682</td>
      </tr>
      <tr>
        <td>CR</td>
        <td>Costa Rica</td>
        <td>+506</td>
      </tr>
      <tr>
        <td>CI</td>
        <td>Côte d'Ivoire</td>
        <td>+225</td>
      </tr>
      <tr>
        <td>HR</td>
        <td>Croatia</td>
        <td>+385</td>
      </tr>
      <tr>
        <td>CU</td>
        <td>Cuba</td>
        <td>+53</td>
      </tr>
      <tr>
        <td>CY</td>
        <td>Cyprus</td>
        <td>+357</td>
      </tr>
      <tr>
        <td>CZ</td>
        <td>Czech Republic</td>
        <td>+420</td>
      </tr>
      <tr>
        <td>CD</td>
        <td>Democratic Republic of Congo</td>
        <td>+243</td>
      </tr>
      <tr>
        <td>DK</td>
        <td>Denmark</td>
        <td>+45</td>
      </tr>
      <tr>
        <td>DJ</td>
        <td>Djibouti</td>
        <td>+253</td>
      </tr>
      <tr>
        <td>DM</td>
        <td>Dominica</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>DO</td>
        <td>Dominican Republic</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>EC</td>
        <td>Ecuador</td>
        <td>+593</td>
      </tr>
      <tr>
        <td>EG</td>
        <td>Egypt</td>
        <td>+20</td>
      </tr>
      <tr>
        <td>SV</td>
        <td>El Salvador</td>
        <td>+503</td>
      </tr>
      <tr>
        <td>GQ</td>
        <td>Equatorial Guinea</td>
        <td>+240</td>
      </tr>
      <tr>
        <td>ER</td>
        <td>Eritrea</td>
        <td>+291</td>
      </tr>
      <tr>
        <td>EE</td>
        <td>Estonia</td>
        <td>+372</td>
      </tr>
      <tr>
        <td>ET</td>
        <td>Ethiopia</td>
        <td>+251</td>
      </tr>
      <tr>
        <td>FK</td>
        <td>Falkland Islands</td>
        <td>+500</td>
      </tr>
      <tr>
        <td>FO</td>
        <td>Faroe Islands</td>
        <td>+298</td>
      </tr>
      <tr>
        <td>FM</td>
        <td>Federated States of Micronesia</td>
        <td>+691</td>
      </tr>
      <tr>
        <td>FJ</td>
        <td>Fiji</td>
        <td>+679</td>
      </tr>
      <tr>
        <td>FI</td>
        <td>Finland</td>
        <td>+358</td>
      </tr>
      <tr>
        <td>FR</td>
        <td>France</td>
        <td>+33</td>
      </tr>
      <tr>
        <td>GF</td>
        <td>French Guiana</td>
        <td>+594</td>
      </tr>
      <tr>
        <td>PF</td>
        <td>French Polynesia</td>
        <td>+689</td>
      </tr>
      <tr>
        <td>GA</td>
        <td>Gabon</td>
        <td>+241</td>
      </tr>
      <tr>
        <td>GE</td>
        <td>Georgia</td>
        <td>+995</td>
      </tr>
      <tr>
        <td>DE</td>
        <td>Germany</td>
        <td>+49</td>
      </tr>
      <tr>
        <td>GH</td>
        <td>Ghana</td>
        <td>+233</td>
      </tr>
      <tr>
        <td>GI</td>
        <td>Gibraltar</td>
        <td>+350</td>
      </tr>
      <tr>
        <td>GR</td>
        <td>Greece</td>
        <td>+30</td>
      </tr>
      <tr>
        <td>GL</td>
        <td>Greenland</td>
        <td>+299</td>
      </tr>
      <tr>
        <td>GD</td>
        <td>Grenada</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>GP</td>
        <td>Guadeloupe</td>
        <td>+590</td>
      </tr>
      <tr>
        <td>GU</td>
        <td>Guam</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>GT</td>
        <td>Guatemala</td>
        <td>+502</td>
      </tr>
      <tr>
        <td>GN</td>
        <td>Guinea</td>
        <td>+224</td>
      </tr>
      <tr>
        <td>GW</td>
        <td>Guinea-Bissau</td>
        <td>+245</td>
      </tr>
      <tr>
        <td>GY</td>
        <td>Guyana</td>
        <td>+592</td>
      </tr>
      <tr>
        <td>HT</td>
        <td>Haiti</td>
        <td>+509</td>
      </tr>
      <tr>
        <td>HN</td>
        <td>Honduras</td>
        <td>+504</td>
      </tr>
      <tr>
        <td>HK</td>
        <td>Hong Kong</td>
        <td>+852</td>
      </tr>
      <tr>
        <td>HU</td>
        <td>Hungary</td>
        <td>+36</td>
      </tr>
      <tr>
        <td>IS</td>
        <td>Iceland</td>
        <td>+354</td>
      </tr>
      <tr>
        <td>IN</td>
        <td>India</td>
        <td>+91</td>
      </tr>
      <tr>
        <td>ID</td>
        <td>Indonesia</td>
        <td>+62</td>
      </tr>
      <tr>
        <td>IR</td>
        <td>Iran</td>
        <td>+98</td>
      </tr>
      <tr>
        <td>IQ</td>
        <td>Iraq</td>
        <td>+964</td>
      </tr>
      <tr>
        <td>IE</td>
        <td>Ireland</td>
        <td>+353</td>
      </tr>
      <tr>
        <td>IL</td>
        <td>Israel</td>
        <td>+972</td>
      </tr>
      <tr>
        <td>IT</td>
        <td>Italy</td>
        <td>+39</td>
      </tr>
      <tr>
        <td>JM</td>
        <td>Jamaica</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>JP</td>
        <td>Japan</td>
        <td>+81</td>
      </tr>
      <tr>
        <td>JO</td>
        <td>Jordan</td>
        <td>+962</td>
      </tr>
      <tr>
        <td>KZ</td>
        <td>Kazakhstan</td>
        <td>+7</td>
      </tr>
      <tr>
        <td>KE</td>
        <td>Kenya</td>
        <td>+254</td>
      </tr>
      <tr>
        <td>KI</td>
        <td>Kiribati</td>
        <td>+686</td>
      </tr>
      <tr>
        <td>XK</td>
        <td>Kosovo</td>
        <td>+381</td>
      </tr>
      <tr>
        <td>KW</td>
        <td>Kuwait</td>
        <td>+965</td>
      </tr>
      <tr>
        <td>KG</td>
        <td>Kyrgyzstan</td>
        <td>+996</td>
      </tr>
      <tr>
        <td>LA</td>
        <td>Laos</td>
        <td>+856</td>
      </tr>
      <tr>
        <td>LV</td>
        <td>Latvia</td>
        <td>+371</td>
      </tr>
      <tr>
        <td>LB</td>
        <td>Lebanon</td>
        <td>+961</td>
      </tr>
      <tr>
        <td>LS</td>
        <td>Lesotho</td>
        <td>+266</td>
      </tr>
      <tr>
        <td>LR</td>
        <td>Liberia</td>
        <td>+231</td>
      </tr>
      <tr>
        <td>LY</td>
        <td>Libya</td>
        <td>+218</td>
      </tr>
      <tr>
        <td>LI</td>
        <td>Liechtenstein</td>
        <td>+423</td>
      </tr>
      <tr>
        <td>LT</td>
        <td>Lithuania</td>
        <td>+370</td>
      </tr>
      <tr>
        <td>LU</td>
        <td>Luxembourg</td>
        <td>+352</td>
      </tr>
      <tr>
        <td>MO</td>
        <td>Macau</td>
        <td>+853</td>
      </tr>
      <tr>
        <td>MK</td>
        <td>Macedonia</td>
        <td>+389</td>
      </tr>
      <tr>
        <td>MG</td>
        <td>Madagascar</td>
        <td>+261</td>
      </tr>
      <tr>
        <td>MW</td>
        <td>Malawi</td>
        <td>+265</td>
      </tr>
      <tr>
        <td>MY</td>
        <td>Malaysia</td>
        <td>+60</td>
      </tr>
      <tr>
        <td>MV</td>
        <td>Maldives</td>
        <td>+960</td>
      </tr>
      <tr>
        <td>ML</td>
        <td>Mali</td>
        <td>+223</td>
      </tr>
      <tr>
        <td>MT</td>
        <td>Malta</td>
        <td>+356</td>
      </tr>
      <tr>
        <td>MH</td>
        <td>Marshall Islands</td>
        <td>+692</td>
      </tr>
      <tr>
        <td>MQ</td>
        <td>Martinique</td>
        <td>+596</td>
      </tr>
      <tr>
        <td>MR</td>
        <td>Mauritania</td>
        <td>+222</td>
      </tr>
      <tr>
        <td>MU</td>
        <td>Mauritius</td>
        <td>+230</td>
      </tr>
      <tr>
        <td>YT</td>
        <td>Mayotte</td>
        <td>+262</td>
      </tr>
      <tr>
        <td>MX</td>
        <td>Mexico</td>
        <td>+52</td>
      </tr>
      <tr>
        <td>MD</td>
        <td>Moldova</td>
        <td>+373</td>
      </tr>
      <tr>
        <td>MC</td>
        <td>Monaco</td>
        <td>+377</td>
      </tr>
      <tr>
        <td>MN</td>
        <td>Mongolia</td>
        <td>+976</td>
      </tr>
      <tr>
        <td>ME</td>
        <td>Montenegro</td>
        <td>+382</td>
      </tr>
      <tr>
        <td>MS</td>
        <td>Montserrat</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>MA</td>
        <td>Morocco</td>
        <td>+212</td>
      </tr>
      <tr>
        <td>MZ</td>
        <td>Mozambique</td>
        <td>+258</td>
      </tr>
      <tr>
        <td>NA</td>
        <td>Namibia</td>
        <td>+264</td>
      </tr>
      <tr>
        <td>NR</td>
        <td>Nauru</td>
        <td>+674</td>
      </tr>
      <tr>
        <td>NP</td>
        <td>Nepal</td>
        <td>+977</td>
      </tr>
      <tr>
        <td>NL</td>
        <td>Netherlands</td>
        <td>+31</td>
      </tr>
      <tr>
        <td>AN</td>
        <td>Netherlands Antilles</td>
        <td>+599</td>
      </tr>
      <tr>
        <td>NC</td>
        <td>New Caledonia</td>
        <td>+687</td>
      </tr>
      <tr>
        <td>NZ</td>
        <td>New Zealand</td>
        <td>+64</td>
      </tr>
      <tr>
        <td>NI</td>
        <td>Nicaragua</td>
        <td>+505</td>
      </tr>
      <tr>
        <td>NE</td>
        <td>Niger</td>
        <td>+227</td>
      </tr>
      <tr>
        <td>NG</td>
        <td>Nigeria</td>
        <td>+234</td>
      </tr>
      <tr>
        <td>NU</td>
        <td>Niue</td>
        <td>+683</td>
      </tr>
      <tr>
        <td>NF</td>
        <td>Norfolk Island</td>
        <td>+672</td>
      </tr>
      <tr>
        <td>KP</td>
        <td>North Korea</td>
        <td>+850</td>
      </tr>
      <tr>
        <td>MP</td>
        <td>Northern Mariana Islands</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>NO</td>
        <td>Norway</td>
        <td>+47</td>
      </tr>
      <tr>
        <td>OM</td>
        <td>Oman</td>
        <td>+968</td>
      </tr>
      <tr>
        <td>PK</td>
        <td>Pakistan</td>
        <td>+92</td>
      </tr>
      <tr>
        <td>PW</td>
        <td>Palau</td>
        <td>+680</td>
      </tr>
      <tr>
        <td>PS</td>
        <td>Palestine</td>
        <td>+970</td>
      </tr>
      <tr>
        <td>PA</td>
        <td>Panama</td>
        <td>+507</td>
      </tr>
      <tr>
        <td>PG</td>
        <td>Papua New Guinea</td>
        <td>+675</td>
      </tr>
      <tr>
        <td>PY</td>
        <td>Paraguay</td>
        <td>+595</td>
      </tr>
      <tr>
        <td>PE</td>
        <td>Peru</td>
        <td>+51</td>
      </tr>
      <tr>
        <td>PH</td>
        <td>Philippines</td>
        <td>+63</td>
      </tr>
      <tr>
        <td>PL</td>
        <td>Poland</td>
        <td>+48</td>
      </tr>
      <tr>
        <td>PT</td>
        <td>Portugal</td>
        <td>+351</td>
      </tr>
      <tr>
        <td>PR</td>
        <td>Puerto Rico</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>QA</td>
        <td>Qatar</td>
        <td>+974</td>
      </tr>
      <tr>
        <td>CG</td>
        <td>Republic of the Congo</td>
        <td>+242</td>
      </tr>
      <tr>
        <td>RE</td>
        <td>Réunion</td>
        <td>+262</td>
      </tr>
      <tr>
        <td>RO</td>
        <td>Romania</td>
        <td>+40</td>
      </tr>
      <tr>
        <td>RU</td>
        <td>Russia</td>
        <td>+7</td>
      </tr>
      <tr>
        <td>RW</td>
        <td>Rwanda</td>
        <td>+250</td>
      </tr>
      <tr>
        <td>BL</td>
        <td>Saint Barthélemy</td>
        <td>+590</td>
      </tr>
      <tr>
        <td>SH</td>
        <td>Saint Helena</td>
        <td>+290</td>
      </tr>
      <tr>
        <td>KN</td>
        <td>Saint Kitts and Nevis</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>MF</td>
        <td>Saint Martin</td>
        <td>+590</td>
      </tr>
      <tr>
        <td>PM</td>
        <td>Saint Pierre and Miquelon</td>
        <td>+508</td>
      </tr>
      <tr>
        <td>VC</td>
        <td>Saint Vincent and the Grenadines</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>WS</td>
        <td>Samoa</td>
        <td>+685</td>
      </tr>
      <tr>
        <td>SM</td>
        <td>San Marino</td>
        <td>+378</td>
      </tr>
      <tr>
        <td>ST</td>
        <td>São Tomé and Príncipe</td>
        <td>+239</td>
      </tr>
      <tr>
        <td>SA</td>
        <td>Saudi Arabia</td>
        <td>+966</td>
      </tr>
      <tr>
        <td>SN</td>
        <td>Senegal</td>
        <td>+221</td>
      </tr>
      <tr>
        <td>RS</td>
        <td>Serbia</td>
        <td>+381</td>
      </tr>
      <tr>
        <td>SC</td>
        <td>Seychelles</td>
        <td>+248</td>
      </tr>
      <tr>
        <td>SL</td>
        <td>Sierra Leone</td>
        <td>+232</td>
      </tr>
      <tr>
        <td>SG</td>
        <td>Singapore</td>
        <td>+65</td>
      </tr>
      <tr>
        <td>SK</td>
        <td>Slovakia</td>
        <td>+421</td>
      </tr>
      <tr>
        <td>SI</td>
        <td>Slovenia</td>
        <td>+386</td>
      </tr>
      <tr>
        <td>SB</td>
        <td>Solomon Islands</td>
        <td>+677</td>
      </tr>
      <tr>
        <td>SO</td>
        <td>Somalia</td>
        <td>+252</td>
      </tr>
      <tr>
        <td>ZA</td>
        <td>South Africa</td>
        <td>+27</td>
      </tr>
      <tr>
        <td>KR</td>
        <td>South Korea</td>
        <td>+82</td>
      </tr>
      <tr>
        <td>ES</td>
        <td>Spain</td>
        <td>+34</td>
      </tr>
      <tr>
        <td>LK</td>
        <td>Sri Lanka</td>
        <td>+94</td>
      </tr>
      <tr>
        <td>LC</td>
        <td>St. Lucia</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>SD</td>
        <td>Sudan</td>
        <td>+249</td>
      </tr>
      <tr>
        <td>SR</td>
        <td>Suriname</td>
        <td>+597</td>
      </tr>
      <tr>
        <td>SZ</td>
        <td>Swaziland</td>
        <td>+268</td>
      </tr>
      <tr>
        <td>SE</td>
        <td>Sweden</td>
        <td>+46</td>
      </tr>
      <tr>
        <td>CH</td>
        <td>Switzerland</td>
        <td>+41</td>
      </tr>
      <tr>
        <td>SY</td>
        <td>Syria</td>
        <td>+963</td>
      </tr>
      <tr>
        <td>TW</td>
        <td>Taiwan</td>
        <td>+886</td>
      </tr>
      <tr>
        <td>TJ</td>
        <td>Tajikistan</td>
        <td>+992</td>
      </tr>
      <tr>
        <td>TZ</td>
        <td>Tanzania</td>
        <td>+255</td>
      </tr>
      <tr>
        <td>TH</td>
        <td>Thailand</td>
        <td>+66</td>
      </tr>
      <tr>
        <td>BS</td>
        <td>The Bahamas</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>GM</td>
        <td>The Gambia</td>
        <td>+220</td>
      </tr>
      <tr>
        <td>TL</td>
        <td>Timor-Leste</td>
        <td>+670</td>
      </tr>
      <tr>
        <td>TG</td>
        <td>Togo</td>
        <td>+228</td>
      </tr>
      <tr>
        <td>TK</td>
        <td>Tokelau</td>
        <td>+690</td>
      </tr>
      <tr>
        <td>TO</td>
        <td>Tonga</td>
        <td>+676</td>
      </tr>
      <tr>
        <td>TT</td>
        <td>Trinidad and Tobago</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>TN</td>
        <td>Tunisia</td>
        <td>+216</td>
      </tr>
      <tr>
        <td>TR</td>
        <td>Turkey</td>
        <td>+90</td>
      </tr>
      <tr>
        <td>TM</td>
        <td>Turkmenistan</td>
        <td>+993</td>
      </tr>
      <tr>
        <td>TC</td>
        <td>Turks and Caicos Islands</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>TV</td>
        <td>Tuvalu</td>
        <td>+688</td>
      </tr>
      <tr>
        <td>UG</td>
        <td>Uganda</td>
        <td>+256</td>
      </tr>
      <tr>
        <td>UA</td>
        <td>Ukraine</td>
        <td>+380</td>
      </tr>
      <tr>
        <td>AE</td>
        <td>United Arab Emirates</td>
        <td>+971</td>
      </tr>
      <tr>
        <td>GB</td>
        <td>United Kingdom</td>
        <td>+44</td>
      </tr>
      <tr>
        <td>US</td>
        <td>United States</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>UY</td>
        <td>Uruguay</td>
        <td>+598</td>
      </tr>
      <tr>
        <td>VI</td>
        <td>US Virgin Islands</td>
        <td>+1</td>
      </tr>
      <tr>
        <td>UZ</td>
        <td>Uzbekistan</td>
        <td>+998</td>
      </tr>
      <tr>
        <td>VU</td>
        <td>Vanuatu</td>
        <td>+678</td>
      </tr>
      <tr>
        <td>VA</td>
        <td>Vatican City</td>
        <td>+39</td>
      </tr>
      <tr>
        <td>VE</td>
        <td>Venezuela</td>
        <td>+58</td>
      </tr>
      <tr>
        <td>VN</td>
        <td>Vietnam</td>
        <td>+84</td>
      </tr>
      <tr>
        <td>WF</td>
        <td>Wallis and Futuna</td>
        <td>+681</td>
      </tr>
      <tr>
        <td>YE</td>
        <td>Yemen</td>
        <td>+967</td>
      </tr>
      <tr>
        <td>ZM</td>
        <td>Zambia</td>
        <td>+260</td>
      </tr>
      <tr>
        <td>ZW</td>
        <td>Zimbabwe</td>
        <td>+263</td>
      </tr>
      </tbody>
    </table>
  </Page>
);

export default Contacts;
